//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMobilePhoneCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderForm
    {
        public string orderID { get; set; }
        public string vendorID { get; set; }
        public string staffID { get; set; }
        public string productID { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
