//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMobilePhoneCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderForm = new HashSet<OrderForm>();
        }
    
        public string ProductID { get; set; }
        public string vendorID { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity { get; set; }
        public string type { get; set; }
        public Nullable<double> price { get; set; }
        public string color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderForm> OrderForm { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
