//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC_OrderForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public string accountID { get; set; }
        public string status { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string role { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
