//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC_OrderForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Bills = new HashSet<Bill>();
            this.CARTs = new HashSet<CART>();
        }
    
        public string customerID { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string accountID { get; set; }
        public string paymentInfo { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<CART> CARTs { get; set; }
    }
}
