//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC_OrderForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOBILEMANAGEMENT : DbContext
    {
        public MOBILEMANAGEMENT()
            : base("name=MOBILEMANAGEMENT")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<DetailOrderForm> DetailOrderForms { get; set; }
        public DbSet<OrderForm> OrderForms { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Vendor> Vendors { get; set; }
        public DbSet<CART> CARTs { get; set; }
        public DbSet<Bill> Bills { get; set; }
        public DbSet<DetailReceipt> DetailReceipts { get; set; }
    }
}
