//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC_OrderForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderForm
    {
        public string orderID { get; set; }
        public string addrress { get; set; }
        public string statusPayment { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
    }
}
