//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC_OrderForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.DetailOrderForms = new HashSet<DetailOrderForm>();
            this.CARTs = new HashSet<CART>();
            this.DetailReceipts = new HashSet<DetailReceipt>();
        }
    
        public string ProductID { get; set; }
        public string vendorID { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity { get; set; }
        public string type { get; set; }
        public Nullable<double> price { get; set; }
        public string color { get; set; }
    
        public virtual ICollection<DetailOrderForm> DetailOrderForms { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<CART> CARTs { get; set; }
        public virtual ICollection<DetailReceipt> DetailReceipts { get; set; }
    }
}
